### ISSUE TITLE
Mappings for device_cost and observation in Truven_CCAE_and_MDCR_ETL_CDM_V5.doc

### ISSUE THREAD

**Issue by donohara** [OHDSI/ETL-CDMBuilder#11]
Is there a newer version of the Truven mapping specs that has the details for the device_cost table, and an update to the observation table section? Device_cost is empty, and observation looks like a previous CDM version.

Thanks!

**Comment by ericaVoss** [comment]
The most up-to-date version can be found here:
https://github.com/OHDSI/ETL-CDMBuilder/blob/master/man/TRUVEN_CCAE_MDCR/Truven_CCAE_and_MDCR_ETL_CDM_V5.doc

We leave costs where they came in.  So true procedure costs stay in PROCEDURE_COST and true drug costs stay in DRUG_COST.  This will all go away when we go to just the one COST table end of this year early next year.

I see what you are saying on the OBSERVATION table.  I will log a ticket on our side - I think the data is already moving from MEASUREMENT to OBSERVATION when needed but we didn't document it.
