### ISSUE TITLE
"Incorrect syntax near GO" when using with SQL Server

### ISSUE THREAD

**Issue by ajmazurie** [OHDSI/ETL-CDMBuilder#12]
Hi,
We are trying to use **ETL-CDMBuilder** to import a Truven database to CDMv5, using SQL Server 2016 as the backend

When running the Building Manager we get an error message `Incorrect syntax near 'GO'` in  `org.ohdsi.cdm.framework.data.DbLayer.DbSource.CreateIndexesChunkTable()`

Looking at http://stackoverflow.com/a/25681013/6621470 it would appear that the `GO` statement should be removed from the various SQL files this code is calling, starting with `CreateIndexesChunkTable.sql`. Is that correct? Did you run into this problem before?

Best, Aurélien

**Comment by bradanton** [comment]
Hi Aurélien,

CreateIndexesChunkTable.sql query has NewLine (\n) symbols after 'GO'
and after below code, GO statement should be removed. I have checked and it works correct on my side.

foreach (var subQuery in query.Split(new[] {"GO" + Environment.NewLine}, StringSplitOptions.RemoveEmptyEntries))
{
  ...
}

Did you use bin or you run from visual studio?

Thanks,
Anton

**Comment by ajmazurie** [comment]
I'm sorry, I'm not certain I understand your answer correctly. Are you asking to remove the `GO` statement in the SQL files, in the C# files, or both?

We compile the project then run the resulting executable from Windows Explorer, not from Visual Studio.

**Comment by bradanton** [comment]
no you don't need to change anything, I found out the cause of issue.
Originally CreateIndexesChunkTable.sql file has CR+LF (Carriage return + Line feed) symbols after GO statement after uploading to github CR+LF was change to LF(Line feed) - for this reason, the code began to work incorrectly. I will try to fix this issue tomorrow. I will let you know when it's ready

**Comment by ericaVoss** [comment]
@ajmazurie - @bradanton  made the fix and I uploaded the change.  Let us know if this helps.
