### ISSUE TITLE
Indices for the input Truven data tables

### ISSUE THREAD

**Issue by pkumar81** [OHDSI/ETL-CDMBuilder#14]
I created tables to load the Truven data (MDCR) and now I am running CDM Builder to convert MDCR data to CDM5 format. Should I create the indices for the input tables (e.g. facility_header, inpatient_services, etc.) before running the CDMBuilder.

**Comment by ericaVoss** [comment]
I would assume that would allow the build to run faster.  It is going to pull data for individual patients so it will query for that data.

**Comment by pkumar81** [comment]
Thank you Erica for the quick response. Could you please provide me the list of indices that need to be created for each table or if you have SQL to create indices for all the input tables, please send me the link for that.
