### ISSUE TITLE
VOCABULARY_ADDITIONS questions

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/ETL-CDMBuilder#17]
I am setting off the ETL-CDMBuilder to convert Truven data to CDMv5, however, I am wondering which of the vocabulary additions are needed to be appended to the source_to_concept. I am assuming both JNJ_TRU_HRA_QUESTION.txt and JNJ_TRU_P_SPCLTY.txt are needed, but they have different formats (one has 8 columns the other one has 9). Also, the text reads: "add the JNJ_TRU_P_SPCLTY file to the records already in SOURCE_TO_CONCEPT_MAP" however, this table is empty when you load the vocabulary, am I missing something that should be here? 

Thanks in advance!

**Comment by ericaVoss** [comment]
Below are the formats of the two files.  The last column in JNJ_TRU_P_SPCLTY is just extra for information purposes.  

We take all our vocabulary files and load them into the SOURCE_TO_CONCEPT_MAP via SQL Bulk Load using the formats below before we start a build.

JNJ_TRU_HRA_QUESTION:
```{SQL}
10.0
9

1	SQLCHAR	0	0	"\t"	1	SOURCE_CODE	""
2	SQLCHAR	0	0	"\t"	2	SOURCE_CONCEPT_ID ""
3	SQLCHAR	0	0	"\t"	3	SOURCE_VOCABULARY_ID ""
4	SQLCHAR	0	0	"\t"	4	SOURCE_CODE_DESCRIPTION	""
5	SQLCHAR	0	0	"\t"	5	TARGET_CONCEPT_ID	""
6	SQLCHAR	0	0	"\t"	6	TARGET_VOCABULARY_ID	""
7	SQLCHAR	0	0	"\t"	7	VALID_START_DATE	""
8	SQLCHAR	0	0	"\t"	8	VALID_END_DATE	""
9	SQLCHAR	0	0	"\r\n"	9	INVALID_REASON	""
```

JNJ_TRU_P_SPCLTY
```{SQL}
10.0
10

1	SQLCHAR	0	0	"\t"	1	SOURCE_CODE	""
2	SQLCHAR	0	0	"\t"	2	SOURCE_CONCEPT_ID ""
3	SQLCHAR	0	0	"\t"	3	SOURCE_VOCABULARY_ID ""
4	SQLCHAR	0	0	"\t"	4	SOURCE_CODE_DESCRIPTION	""
5	SQLCHAR	0	0	"\t"	5	TARGET_CONCEPT_ID	""
6	SQLCHAR	0	0	"\t"	6	TARGET_VOCABULARY_ID	""
7	SQLCHAR	0	0	"\t"	7	VALID_START_DATE	""
8	SQLCHAR	0	0	"\t"	8	VALID_END_DATE	""
9	SQLCHAR	0	0	"\t"	9	INVALID_REASON	""
10	SQLCHAR	0	0	"\r\n"	0	DESCRIPTION	""
```
