### ISSUE TITLE
Working version

### ISSUE THREAD

**Issue by globallyunique** [OHDSI/ETL-CDMBuilder#19]
The latest commit doesn't seem to work for Truven source data due to conflicts in the code and the database that is created by the various scripts, e.g., the SubChunks table isn't there but the code expects it.  The code related to Achilles also causes exceptions.  I'm using SqlServer as the database for all schemas, e.g., Builder, Vocabulary, CDM, etc.  Is the current commit or any earlier one something that can be built and run from source code?  I've tried the Oct 17 version and it doesn't work in similar ways.

**Comment by alondhe** [comment]
Can you provide some of the error messages you're seeing?

**Comment by globallyunique** [comment]
First I need to comment out in Building.cs the lines like the following and
make other changes where it writes Achilles records or it throws an
exception:

AchillesStart = reader.GetDateTime("AchillesStart");

This is probably related to not knowing how it expects the Achilles code to
run.  I have R and R-Studio and I've successfully run the Achilles.R file
in R Studio to prove that the libraries load.

I needed to add creation of the SubChunks table or it throws an exception
because the table isn't present then un-comment the following line in
ChunkController.cs or it throws an exception because the SubChunks table is
empty.

AddSubChunks(chunkId, chunk);

**Comment by globallyunique** [comment]
For an example of a specific exception, I went back to the Oct 17 commit
and after commenting out the AchillesStart and AccillesEnd lines in
Building.cs I get the following exception:

Builder: IE10WIN7
Time: Mar  3 2017 11:45AM
Error: Exception Found:
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: org.ohdsi.cdm.framework.data
Stacktrace:    at
org.ohdsi.cdm.framework.data.DbLayer.DbSource.<GetPersonKeys>d__7.MoveNext()
in
C:\Users\IEUser\ETL-CMDBuilder\source\Framework\org.ohdsi.cdm.framework.data\DbLayer\DbSource.cs:line
69
   at
org.ohdsi.cdm.framework.core.Controllers.ChunkController.<GetPersonKeys>d__17.MoveNext()
in
C:\Users\IEUser\ETL-CMDBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\ChunkController.cs:line
267
   at
org.ohdsi.cdm.framework.core.Controllers.ChunkController.CreateChunks() in
C:\Users\IEUser\ETL-CMDBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\ChunkController.cs:line
88
   at
org.ohdsi.cdm.framework.core.Controllers.BuilderController.PerformAction(Action
act) in
C:\Users\IEUser\ETL-CMDBuilder\source\Framework\org.ohdsi.cdm.framework.core\Controllers\BuilderController.cs:line
80
