### ISSUE TITLE
Conversion from RAW to CDM - Batch number not changing

### ISSUE THREAD

**Issue by pkumar81** [OHDSI/ETL-CDMBuilder#25]
We are running ETL CDM Builder to convert Truven CCAE data to CDM format. The CDM Builder has been running for 8 days, but today the fourth step 'Conversion from RAW to CDM' got stuck at batch number 256447. It has been running for more than 2.5 hours and batch number 256447 is still unfinished. Our batch size is 512 and it usually takes a few seconds to process one batch.
Can anyone please let me know how to fix this issue?

![cdmbuilder](https://cloud.githubusercontent.com/assets/16943656/25249097/dd4ca0a4-25cd-11e7-8492-9b4a14d275eb.png)

**Comment by bradanton** [comment]
Hi,
You can do to try following:
1. Stop conversion (press stop button) then close application
2. Using task manager kill all process like: org.ohdsi.cdm.presentation.builderprocess.exe and org.ohdsi.cdm.presentation.buildingmanager.exe
3. Open builder again, right mouse click on "Conversion from RAW to CDM" -> "Reset not finished chunks"
4. Start conversion

**Comment by pkumar81** [comment]
Thank you Bradanton. The steps you have mentioned solved the problem. CDM Builder processed all the batches. 
![image](https://cloud.githubusercontent.com/assets/16943656/25293748/7266f830-2699-11e7-8c03-28bb8f0c561d.png)
