### ISSUE TITLE
ETL-CDMBuilder INPATIENT_SERVICES table issue

### ISSUE THREAD

**Issue by dantohe** [OHDSI/ETL-CDMBuilder#43]
ETL-CDMBuilder INPATIENT_SERVICES table issue

The builder is expecting a column (dx5) that doesn’t seem to exists in Truven CCAE (2015) data.
https://github.com/OHDSI/ETL-CDMBuilder/blob/master/source/Builders/org.ohdsi.cdm.builders.truven_v5/TruvenV5/Definitions/INPATIENT_SERVICES.xml

Error from  Source: Amazon Redshift ODBC Driver:  Message: ERROR [42703] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42703] ERROR:  column "dx5" does not exist in inpatient_services, ch, unnamed_join

The following columns are part of these data (taken from the Truven sample data):
SEQNUM	VERSION	DX1	DX2	DXVER	PROC1	PROCTYP	CASEID	DISDATE	DOBYR	YEAR	ADMDATE	AGE	CAP_SVC	COB	COINS	COPAY	DEDUCT	DRG	DX3	DX4	FACHDID	FACPROF	MHSACOVG	MSCLMID	NETPAY	NPI	NTWKPROV	PAIDNTWK	PAY	PDDATE	PDX	PPROC	PROCMOD	PROVID	QTY	REVCODE	SVCDATE	SVCSCAT	TSVCDAT	UNITS	ADMTYP	MDC	DSTATUS	STDPLAC	STDPROV	EFAMID	ENROLID	PLANTYP	REGION	MSA	DATATYP	AGEGRP	EECLASS	EESTATU	EGEOLOC	EIDFLAG	EMPREL	ENRFLAG	PHYFLAG	RX	SEX	HLTHPLAN	INDSTRY

**Comment by dantohe** [comment]
@ericaVoss - thanks - the trick worked - now I am getting a few other issues and the logging is kind of cryptic for some of them.

**Issue#1 – I assume it is a missing table – how can I create this table?**
Message: ERROR [42P01] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42P01] ERROR:  relation "truven.hra_variable_ref" does not exist
Source: Amazon Redshift ODBC Driver
Stacktrace:    at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode)

**Issue#2 – potential DDL mismatch – I assume in the raw Truven data table – any feedback will be appreciated as the log is very cryptic and doesn’t point toward where the issue is**
Error: Exception Found:
Type: System.Data.Odbc.OdbcException
Message: ERROR [22P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 22P02] ERROR:  invalid input syntax for integer: ""
Source: Amazon Redshift ODBC Driver

**Issue#3 – similar with #2: potential DDL mismatch – I assume in the raw Truven data table – any feedback will be appreciated as the log is very cryptic and doesn’t point toward where the issue is**
Error: Exception Found:
Type: System.Data.Odbc.OdbcException
Message: ERROR [42804] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42804] ERROR:  CASE types integer and text cannot be matched
Source: Amazon Redshift ODBC Driver
bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at org.ohdsi.cdm.framework.core.Controllers.ChunkController.MoveChunkDataToS3(IEnumerable`1 chunkIds)
  Source: mscorlib

Any help is greatly appreciated.

Daniel

**Comment by ericaVoss** [comment]
### Issue#1
Do you purchase HRA data from Truven?  I think it comes from the PDFs they send and we made a table from it.  But see comment below . . . 

### Issue#2
### Issue#3
Could you email me at evoss3 AT its.jnj.com?  Let's ask Truven if we can share our DDL with you.  They have to approve the sharing of anything.

**Comment by dantohe** [comment]
Erica - thank you! We do appreciate your help - I sent an email.
Daniel

**Comment by bradanton** [comment]
Hi Daniel,

**Issue#1**
If you don't have HRA data you can simple remove file {BuilderFolder}\TruvenV5\Definitions\HEALTH_RISK_ASSESSMENT.xml and HRA will be skipped.

**Issue#2** and **Issue#3**
Lets try to do following.
1) Fix **Issue#1**
2) Cleanup builder log. Run following in Builder database: delete FROM [Log]
3) Run CDM Buiilder again.
4) And finally, I need log details it should help to resolve the issues.  
SELECT
  [Type],
  [Time],
  [Message]
FROM [Log]
ORDER BY [Time]

Thanks,
Anton

**Comment by dantohe** [comment]
Anton,
Thanks a lot for help!
I did as per instructions and I am getting the following log (still I cannot pinpoint the culprit  location/query - maybe you can):
Id          ChunkId     BuilderId   Type                                               Time                    Message                                                                                                                                                                                                                                                          BuildingId
----------- ----------- ----------- -------------------------------------------------- ----------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -----------
37          NULL        1           Error                                              2018-08-13 09:42:02.687 Exception Found:
Type: System.OutOfMemoryException
Message: Exception of type 'System.OutOfMemoryException' was thrown.
Source: mscorlib
Stacktrace:    at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 v 4
38          141         1           Error                                              2018-08-13 09:43:14.477 Exception Found:
Type: System.Data.Odbc.OdbcException
Message: ERROR [42804] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42804] ERROR:  CASE types integer and text cannot be matched

Source: Amazon Redshift ODBC 4
39          155         1           Error                                              2018-08-13 09:43:14.483 Exception Found:
Type: System.Data.Odbc.OdbcException
Message: ERROR [42804] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 42804] ERROR:  CASE types integer and text cannot be matched

Source: Amazon Redshift ODBC 4
40          155         1           Error                                              2018-08-13 09:43:14.527 Exception Found:
Type: System.Data.Odbc.OdbcException
Message: ERROR [22P02] [Amazon][Amazon Redshift] (30) Error occurred while trying to execute a query: [SQLState 22P02] ERROR:  invalid input syntax for integer: ""

Source: Amazon Redshift ODBC Driver
S 4
41          NULL        1           Error                                              2018-08-13 09:43:56.330 Exception Found:
Type: System.AggregateException
Message: One or more errors occurred.
Source: mscorlib
Stacktrace:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 mi 4

(5 rows affected)

**Comment by bradanton** [comment]
Hi Daniel,

hmm.. log did not help much. Looks like schema mismatch, some INT NOT NULL field has empty string value.

Okay, is it possible to send me your CCAE tables schema?

**Comment by ericaVoss** [comment]
@bradanton  - I'm working with Truven to share our DDL, we need to get permission from them.

**Comment by dantohe** [comment]
@bradanton @ericaVoss 
Indeed this is what I thought myself - there are mismatches between your Truven CCAE schema and ours - our was build by somebody for another project using some reverse engineering after being imported in MS Access.
I can definitely share my schema while we are waiting for Truven/IBM to approve sharing the schema with us.
Anton - since I do not have your email I can send it to Erica and she can forward it to you.
Again - thanks a lot for your help.
Daniel

**Comment by ericaVoss** [comment]
@dantohe please do not share the schema until we get permission from Truven.  I have a meeting with them Thursday.

**Comment by dantohe** [comment]
![image](https://user-images.githubusercontent.com/11204633/44682871-d892f900-aa01-11e8-89a1-21dc2a1db287.png)
