### ISSUE TITLE
Help with ETL CMD Builder

### ISSUE THREAD

**Issue by paulinem11** [OHDSI/ETL-CDMBuilder#45]
Dear All,

I am a new user of OHDSI tools and I am a little bit confused on the way on how to use it.
I would like to convert observational databases (CPRD in my case) in CDM OMOP. 

I have downloaded the ETL CMD builder on Guithub (which seems to be the adapted tool) and try to launch the application (org.ohdsi.cdm.presentation.buildingmanager.exe) as indicated. But a SQL server seems to be mandatory to use this tool, isn’t it? 
Is there any way to use ETL CMD builder without SQL server but using flat files for example?

Many thanks for your help.

Pauline

**Comment by ericaVoss** [comment]
@paulinem11 

We share our CDM_BUILDER as an example - however it wasn't initially developed with the open-source community in mind.  So it is expecting the environment we have here.  

@bradanton is on vacation but might have some additional comments.

Or @alondhe.

**Comment by alondhe** [comment]
Hi @paulinem11, SQL Server or Amazon Redshift are the only ways to use this particular CDM Builder. There is a newer version that is coming soon that allows for building off of flat file chunks hosted in Amazon S3, but then that requires using Amazon Lambda for serverless computations. Perhaps this method could help, but of course, you'd need to utilize those 2 Amazon Web Services products.

Once our lead developer is back from vacation, we can make a more concrete timeline as for when this Lambda-based builder will be available to the OHDSI community.

**Comment by paulinem11** [comment]
@ericaVoss @alondhe thanks for your reply
It is clearer for me now. As I don't have SQL server for now, I will try to find another way to convert my CPRD database in CDM.

**Comment by bradanton** [comment]
@paulinem11 Currently CDM Builder cant work with flat files. Potentially I can upgrade builder to read from flat file, but anyway records in files must be ordered by person_id field and split but chunks. 
What are you going to use for CDM data storage, flat file as well?

**Comment by paulinem11** [comment]
Thanks @bradanton  for your reply.
For CDM data storage we will use flat file. 
I am going to see with the team if we can have a SQL server and then use your tool.
If not possible, when do you think the upgrade of CDM builder with flat file will be available?
