### ISSUE TITLE
CDM Builder DDL needs review for  Payer Plan Period / Achilles analysis 1424

### ISSUE THREAD

**Issue by djb2188** [OHDSI/ETL-CDMBuilder#51]
###Expected behavior
DDL is compliant with current Achilles version and analysis id 1425
###Actual behavior
DDL from .net ETL Builder seems to vary from schema that Achilles expects when processing analysis 1425 / table payer_play_period aggregation
 ###Steps to reproduce behavior
Run Achilles  analysis 1425 using Achilles/Master

###Notes
Please see ticket open on Achilles Repo
@alondhe @t-abdul-basser

**Comment by bradanton** [comment]
Hi David,

The ETL-CDMBuilder has supports only CDM version 5.2,
you need to use https://github.com/OHDSI/ETL-LambdaBuilder it has desktop version as well.

@alondhe @t-abdul-basser

**Comment by djb2188** [comment]
Thank you @bradanton. This builder is only for data movement on AWS yes?  I appreciate your help.

@cukarthik @alondhe

**Comment by bradanton** [comment]
@djb2188 ETL-LambdaBuilder supports both AWS Redshift and MS SQL
