### ISSUE TITLE
wrong operator_concept_id

### ISSUE THREAD

**Issue by liyupeng111** [OHDSI/ETL-CDMBuilder#53]
In the document "man/OPTUM_EXTENDED/v5.3.0/ETL/measurement.md",
 
when '<' then operator_concept_id = 4172704
when '>' then operator_concept_id = 4171756

However, 4172704 is '>' and 4171756 is '<'.

**Comment by clairblacketer** [comment]
Thanks so much! We recently updated the documentation, located [here](https://ohdsi.github.io/ETL-LambdaBuilder/docs/Optum_Clinformatics). We didn't bring the operators over to the new document but I will add it as an issue.
