### ISSUE TITLE
Connecting to mssql server DB does not work as before

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/ETL-CDMBuilder#55]
With the previous version (before December, Friday 03/2020) my mssql server db settings were working well in the sense that the builder always saw the databases. Now, I got the next error:

```
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.PerformAction(Action act) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 55
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.<>c.<CreateDestination>b__9_0() in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 75
   at org.ohdsi.cdm.framework.desktop.DbLayer.DbDestination.CreateDatabase(String query) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.framework.desktop\DbLayer\DbDestination.cs:line 42
   at System.Data.Odbc.OdbcCommand.ExecuteNonQuery()
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
Stacktrace:    at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode)
Source: sqlncli11.dll
Message: ERROR [42000] [Microsoft][SQL Server Native Client 11.0]Syntax error, permission violation, or other nonspecific error
Type: System.Data.Odbc.OdbcException
12/4/2020 11:44:33 AM| Exception Found:
```

The latest version ask for a schema but it was not needed in previous versions. I also entered my DB settings as:

    <add name="SourceConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={localhost};Database={Truven_mdcr};Uid={sa};Pwd={somepwd};" />
    <add name="DestinationConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={localhost};Database={JoseTruvenmdcrDest};Uid={sa};Pwd={somepwd};" />
    <add name="VocabularyConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={localhost};Database={Vocab};Uid={sa};Pwd={somepwd};" />
 
 My vendor setting is:

`    

    <add key="Vendor" value="MDCR" />

    <add key="PersonBuilder" value="org.ohdsi.cdm.framework.etl.ibm.IbmPersonBuilder, org.ohdsi.cdm.framework.etl.ibm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
    `   

and the error still continued. Also, the interface does not offer a drop down list for vendors anymore and the error log refers to a E: disk drive unit and I only have a C: drive,

Thanks

**Comment by bradanton** [comment]
1. You don't need to change connection string templates:

Driver={SQL Server Native Client 11.0};Server=**{server}**;Database=**{database}**;Uid=**{username}**;Pwd=**{password}**;

{server}, {database}, {username}, {password} these values will take from UI.

In you case will be:
`
<add name="SourceConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={server};Database={database};Uid={username};Pwd={password};" />
<add name="DestinationConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={server};Database={database};Uid={username};Pwd={password};" />
<add name="VocabularyConnectionStringTemplate" connectionString="Driver={SQL Server Native Client 11.0};Server={server};Database={database};Uid={username};Pwd={password};" />
`

You needs to change template only if you want to use another driver, for example:
for example: Driver={ODBC Driver 17 for SQL Server};Server={server}={database};UID={username};PWD={password};

2. I will take a look about E: drive.

**Comment by jcabrerazuniga** [comment]
I use the next config on the interface:

Source Settings:
Server name: localhost
DB Name: Truven_mdcr
Schema Type:
Username: sa
Password: *************

CDM Settings:
Server name: localhost
DB Name: JoseTruven_mdcrDest
Schema Type:
Username: sa
Password: *************

Vocabulary Settings:
Server name: localhost
DB Name: Vocab
Schema Type:
Username: sa
Password: *************

and the template I modified is attached:
[org.ohdsi.cdm.presentation.builder.dll.config.zip](https://github.com/OHDSI/ETL-CDMBuilder/files/5680256/org.ohdsi.cdm.presentation.builder.dll.config.zip)


Yet, I get the error:
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.PerformAction(Action act) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 55
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.<>c.<CreateDestination>b__9_0() in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 74
Stacktrace:    at org.ohdsi.cdm.framework.desktop.DbLayer.DbDestination.CreateDatabase(String query) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.framework.desktop\DbLayer\DbDestination.cs:line 47
Source: org.ohdsi.cdm.framework.desktop
Message: Object reference not set to an instance of an object.
Type: System.NullReferenceException
12/11/2020 9:05:57 AM| Exception Found:

Any suggestions please?

Thanks
Jose C. Cabrera Zuniga

**Comment by bradanton** [comment]
Hi Jose,

You need to specify schema name for source, CDM and vocabulary databases. (For MS SQL dbo schema is the default schema).

Thanks,
Anton

**Comment by jcabrerazuniga** [comment]
You are correct @bradanton. After I placed dbo as the default schema all started to run!
