### ISSUE TITLE
Error messages I do not understand

### ISSUE THREAD

**Issue by jcabrerazuniga** [OHDSI/ETL-CDMBuilder#56]
Hi again
     I started the latest version of the ETL-CDMBuilder and I got the next error messages. Can someone tell me what to look at? I am trying to convert a Truven mdcr database and my configuration file is at:

[org.ohdsi.cdm.presentation.builder.dll.config.zip](https://github.com/OHDSI/ETL-CDMBuilder/files/5690569/org.ohdsi.cdm.presentation.builder.dll.config.zip)

Could this be related to the number of chunks or "Degree of Parallelism"?

My truven_mdcr database has an enrollment_detail table that is descried as:

Truven_mdcr	dbo	enrollment_detail	age	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	1	YES	38
Truven_mdcr	dbo	enrollment_detail	agegrp	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	2	YES	39
Truven_mdcr	dbo	enrollment_detail	datatyp	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	3	YES	38
Truven_mdcr	dbo	enrollment_detail	dobyr	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	4	YES	38
Truven_mdcr	dbo	enrollment_detail	dtend	-9	date	10	20	NULL	NULL	1	NULL	NULL	-9	NULL	NULL	5	YES	0
Truven_mdcr	dbo	enrollment_detail	dtstart	-9	date	10	20	NULL	NULL	1	NULL	NULL	-9	NULL	NULL	6	YES	0
Truven_mdcr	dbo	enrollment_detail	eeclass	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	7	YES	39
Truven_mdcr	dbo	enrollment_detail	eestatu	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	8	YES	39
Truven_mdcr	dbo	enrollment_detail	efamid	4	int	10	4	0	10	1	NULL	NULL	4	NULL	NULL	9	YES	38
Truven_mdcr	dbo	enrollment_detail	egeoloc	-8	nchar	2	4	NULL	NULL	1	NULL	NULL	-8	NULL	4	10	YES	39
Truven_mdcr	dbo	enrollment_detail	empcty	4	int	10	4	0	10	1	NULL	NULL	4	NULL	NULL	11	YES	38
Truven_mdcr	dbo	enrollment_detail	emprel	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	12	YES	39
Truven_mdcr	dbo	enrollment_detail	empzip	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	13	YES	38
Truven_mdcr	dbo	enrollment_detail	enrolid	-5	bigint	19	8	0	10	1	NULL	NULL	-5	NULL	NULL	14	YES	108
Truven_mdcr	dbo	enrollment_detail	hlthplan	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	15	YES	39
Truven_mdcr	dbo	enrollment_detail	indstry	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	16	YES	39
Truven_mdcr	dbo	enrollment_detail	memdays	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	17	YES	38
Truven_mdcr	dbo	enrollment_detail	mhsacovg	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	18	YES	39
Truven_mdcr	dbo	enrollment_detail	msa	4	int	10	4	0	10	1	NULL	NULL	4	NULL	NULL	19	YES	38
Truven_mdcr	dbo	enrollment_detail	phyflag	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	20	YES	39
Truven_mdcr	dbo	enrollment_detail	plankey	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	21	YES	38
Truven_mdcr	dbo	enrollment_detail	plantyp	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	22	YES	38
Truven_mdcr	dbo	enrollment_detail	region	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	23	YES	39
Truven_mdcr	dbo	enrollment_detail	rx	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	24	YES	39
Truven_mdcr	dbo	enrollment_detail	seqnum	-5	bigint	19	8	0	10	1	NULL	NULL	-5	NULL	NULL	25	YES	108
Truven_mdcr	dbo	enrollment_detail	sex	-8	nchar	1	2	NULL	NULL	1	NULL	NULL	-8	NULL	2	26	YES	39
Truven_mdcr	dbo	enrollment_detail	version	-8	nchar	2	4	NULL	NULL	1	NULL	NULL	-8	NULL	4	27	YES	39
Truven_mdcr	dbo	enrollment_detail	wgtkey	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	28	YES	38
Truven_mdcr	dbo	enrollment_detail	year	5	smallint	5	2	0	10	1	NULL	NULL	5	NULL	NULL	29	YES	38

and my Vocab database does not show any Enrollment_Detail table

Thanks
Jose

ERRROR MESSAGES:
 at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.<>c__DisplayClass18_0.<Build>b__2(Int32 chunkId, ParallelLoopState state) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 303
  Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
  Source: org.ohdsi.cdm.presentation.builder
  Message: Input string was not in a correct format.
  Type: System.FormatException
  Inner Exception Found:
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.PerformAction(Action act) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 55
   at org.ohdsi.cdm.presentation.builder.Controllers.BuilderController.<>c__DisplayClass18_0.<Build>b__0() in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Controllers\BuilderController.cs:line 289
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`2 body)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
Stacktrace:    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
Source: System.Threading.Tasks.Parallel
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.)
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: One or more errors occurred. (Input string was not in a correct format.) (ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.AggregateException
12/14/2020 10:29:39 AM| Exception Found:
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:39 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:39 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:35 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:35 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:34 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:34 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:31 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:30 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:27 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:27 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:26 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:26 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine
Stacktrace:    at org.ohdsi.cdm.presentation.builder.Base.DatabaseChunkBuilder.Process(IDatabaseEngine sourceEngine, String sourceSchemaName, List`1 sourceQueryDefinitions, OdbcConnection sourceConnection, String vendor) in E:\repo\ohdsi\ETL-CDMBuilder\source\org.ohdsi.cdm.presentation.builder\Base\DatabaseChunkBuilder.cs:line 48
Source: sqlncli11.dll
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'ethnicity_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_concept_id'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'race_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'vendor'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_source_value'.
ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'observation_concept_id'.
Message: ERROR [42S22] [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'payersource'.
Type: System.Data.Odbc.OdbcException
12/14/2020 10:29:24 AM| Exception Found:

Query:
File name=ENROLLMENT_DETAIL
SourceConnectionString=
12/14/2020 10:29:24 AM| SourceEngine=org.ohdsi.cdm.framework.desktop.Databases.MssqlDatabaseEngine

**Comment by bradanton** [comment]
Hi Jose,

I just added hot fix for the MDCR and MS SQL. (../ETL/IBM/Definitions/ENROLLMENT_DETAIL.xml - was updated)
Please try latest version.

Thanks,
Anton

**Comment by jcabrerazuniga** [comment]
I am now using the latest version you posted and the error messages are not showing up anymore. I am also crossing my fingers as my conversion from mdcr to ccae is running at present. With the previous version the conversion from mdcr->cdm failed at the "Copying Dictionary Section" so I am still expecting another problem. 

Thanks
Jose
