### ISSUE TITLE
Process Just Stops

### ISSUE THREAD

**Issue by Prussian1870** [OHDSI/ETL-CDMBuilder#6]
Hi Erica:

I setup the converter to do a CDM4 conversion from Truven Medicare data. The tool created the cdm4 db and populated the provider information but care_site and location were all populated with records of 0 for their primary keys. None of the person, condition_occurrence, drug_exposure or visit_occurrence data was populated. There were no errors either. I do have a v4 vocabulary DB setup as well. All my Truven data tables are populated with exception of lab data.

Do you have any insight as to why this maybe happening?

Thanks

Jorge

**Comment by bradanton** [comment]
Hi Jorge,

What values are you used in following fields: MaxDegreeOfParallelism, BatchSize and Number of batches?

Thanks,
Anton

**Comment by ericaVoss** [comment]
@Prussian1870 - we have deployed a new copy of the builder that is in the CDM v5 format.  This may be helpful.
