### ISSUE TITLE
Source code no longer on github?

### ISSUE THREAD

**Issue by donohara** [OHDSI/ETL-CDMBuilder#7]
Has the source code for ETL-CDMBuilder been removed from github? I only see the dll and exe files. Does this mean I no longer have to build it ?

**Comment by ericaVoss** [comment]
You should just be able to click the .exe file under the source folder.

**Comment by donohara** [comment]
Thanks - Thought I was going nuts since I previously downloaded all the src and no longer see it...

**Comment by donohara** [comment]
I see all the c# source code under the CDMv4/source directory. Will the v5 source be added to the repo as well? We prefer building the .exe in house if possible.

**Comment by ericaVoss** [comment]
I don't see why not.  When we do our next posting I'll look to do that.

**Comment by ericaVoss** [comment]
The source is now posted:
https://github.com/OHDSI/ETL-CDMBuilder/tree/master/source
